### ISSUE TITLE
What does `Free Trial` mean?

### ISSUE THREAD

**Issue by iahunq** [cxasm/notepad--#189]
On `About Notepad--` I saw `Free Trial`. On `Feedback` menu I also saw `Register` button. Does it mean this software is commercial? What is the different between `Free Trial` and `Registered` version?

**Comment by cxasm** [comment]
It was a matter of necessity. It is a reality that no matter you are doing open source software or commercial software, it is very easy to face no income in China due to piracy.

First of all, we follow the gpl protocol as much as possible. The main program functions are open source, and some plug-in functions are closed source. As a result, as independent software, it is not profitable in China. Unless you're a big company, big software, that can afford a team, ndd doesn't have that.

Instead of making a paid software with no users, making a "commercial software" with no mandatory fees, where ndd is commercial software, but it can be used for free, is our strategy. We're not going to say you can't use it unless you pay for it. We advocate: you are rich, you are willing to pay, you pay; You're in financial trouble. You can use it for free. This is more in line with the Chinese market.

Many people do not realize that open source software is not free software and can be monetized through commercial activities. So the strategy for ndd is, like most of its commercial peers -- the basic, or educational, edition is free and open source. But the Pro version costs money, and some advanced plug-ins are closed source, such as the comparison function. In this way we do not violate the gpl agreement, but also provide a possibility and hope for future commercial success.

So free trial means that the software is free to use, but it's commercial software in general. But there is no mandatory requirement for users to purchase a registration code. In the future, some advanced features may be available only in a paid mode. The current version does not have these limitations, and the free version and the registered version have the same functionality.

以下是中文回复：

这是迫不得已的事情。无论是做开源软件，还是做商业软件，在国内因为盗版问题，很容易面临没有收入的境地，这是现实。

首先我们尽可能的遵循了gpl协议，主程序功能是开源的，部分插件功能闭源。这样一来，作为独立软件，在中国是无法盈利的。除非是大公司，大软件，能够养得起团队，ndd没有这样的条件。

与其做一个没有用户的收费软件，不如做一个不强制收费的“商业软件”，即ndd是商业软件，但是也可以免费使用，这是我们的策略。我们不会说，你不付费就不能使用。我们提倡：你富有，你愿意付费，你就付费；你经济困难，你可以免费使用。这更符合中国的市场。

许多人没有意识到，开源软件并不是免费软件，是可以通过商业行为来进行盈利的。所以ndd的策略是，类似大部分同行商业软件一样——基础版，或者说教育版是免费的，而且是开源的。但是专业版是要收费的，而且部分高级插件是闭源的，比如对比功能。这样我们即没有违反gpl协议，也为未来面向商业成功提供一种可能和希望。

所以免费试用，表示软件可以免费使用，但是它总体而言是商业软件。不过没有强制需要用户购买注册码而已。未来有部分高级功能，可能是要在收费模式下才能使用。目前版本并没有这些功能限制，免费版本和注册版本的功能是一样的。
