### ISSUE TITLE
Support Language Server Protocol

### ISSUE THREAD

**Issue by superchick** [cxasm/notepad--#348]

**Comment by cxasm** [comment]
I don't want to respond much to the other topics. The code for Notepad-- refers to open source code from competitors, such as notepadNext. But saying that Notepad-- is plagiarism is untenable. Notepad-- is implemented based on the Qt framework, while almost all other competitors use Windows programming under Win32, making it impossible to clone or plagiarize. For example, if you have a house and I also build one, although it looks similar and has a reference appearance, there is no possibility of plagiarism.


There are not only Windows systems in the world, but China also has its own deep and Kirin systems. In the future, there will be Huawei HarmonyOS PC operating system, and Ndd will first support domestic operating systems. 300 years ago, China was leading the world in technology, and foreigners were learning from China. In the past 100 years, China's technology has lagged behind, but in the next 50 years, China's technology will definitely surpass the world, and European and American foreigners will come to learn from us. When we oppose and surpass our competitors, the so-called plagiarism remarks will be self-evident. For Europe and America, 300 years is a long history, but for China, it is a relatively short history. We have a written history of over 2000 years, so falling behind by 100 years in a short period of time is not a big problem for a nation and country with a history of 5000 years.


We just want to focus on doing our own things well now. When others say we imitate and plagiarize, we don't stop because of it.

 其余的话题我不想多回应。Notepad--的代码有参考竞品的开源代码，比如notepadNext这些等。但是说Notepad--是抄袭，是站不住脚的。Notepad--是基于Qt框架来实现的，其余竞品几乎都是win32 下windows编程，是不可能克隆或抄袭的。好比你有一座房子，我也建一座房子，虽然看起来外观相似，外观有参考，但是不存在抄袭的可能。

世界上不仅仅只有windows系统，中国也有自己的深度和麒麟系统，未来还有华为鸿蒙PC操作系统，Ndd是首先要支持国产操作系统。中国在300年前，科技曾经领先世界，外国人都学习中国。最近100多年，中国科技落后了，但是未来50年，中国科技一定会反超世界，到时候欧美外国人还会来学习我们。当我们反超竞争对手的时候，所谓抄袭的言论将不攻自破。300年对欧美而言，是一段很长的历史，但是对中国而言，是一段较短的历史。我们有文字记载的历史，都超过2000年，所以短时间落后100年，对一个有5000年历史的民族和国家来说，不算太大的问题。

我们现在只想专心做好自己的事情，当别人说我们模仿和抄袭的时候，我们并不会因此停下脚步。
